Document new max return payload size setting
STORIS/mvom pull request #359
Opened 2023-01-27 22:16 UTC by kthompson23

This PR documents the new maximum return payload size parameter introduced in [357](https://github.com/STORIS/mvom/pull/357).

I removed the default value on each of the method documentation and indicated that the value specified at connection creation would be used. I also fleshed out the explanation on the create connection documentation.

2023-01-27 22:35 UTC, shawnmcknight commented on website/docs/02 - Connection.md
> +| `maxReturnPayloadSize` | `number`      | `100_000_000` | The maximum allowed return payload size in bytes. If this size is exceeded a DbServerError will be thrown. Returning large payloads can have
Typo -- `improperty`

2023-01-27 22:37 UTC, shawnmcknight requested changes
Looks good.  Just the one typo noted.

2023-01-27 23:50 UTC, kthompson23 commented on website/docs/02 - Connection.md
> +| `maxReturnPayloadSize` | `number`      | `100_000_000` | The maximum allowed return payload size in bytes. If this size is exceeded a DbServerError will be thrown. Returning large payloads can have
updated.

2023-01-27 23:50 UTC, kthompson23 commented
I fixed the issue. This is ready for another look.

2023-01-28 12:59 UTC, shawnmcknight approved these changes
LGTM!

2023-03-16 15:46 UTC, merged