Allow bypassing deployment validation and expose basic subroutine name on connection instance
STORIS/mvom pull request #709
Opened 2024-06-28 01:25 UTC by shawnmcknight

This PR makes the following changes:

#### Allow bypassing deployment validation
A new `validateDeployment` property has been added to the `open` method options on the `Connection` class. This option, which defaults to `true`, indicates that the database server's required mvom subroutine will be validated prior to opening the connection. This validation consists of checks to ensure that the MVIS subroutine definition exists and that the subroutine has been cataloged on the server.

If this option is overridden to `false`, this check will be bypassed and the connection will attempt to be opened.

#### Expose multivalue subroutine name on `Connection`
A new public property has been added to the `Connection` object named `subroutineName`. This is a public getter which will return the name of the subroutine as determined by the `DeploymentManager` instance associated with the `Connection`. This property can be accessed by consumers to determine what the name of the subroutine used by mvom when communicating through MVIS to the database server is.

2024-07-01 16:10 UTC, philfuster requested changes
This looks good to me. I just noticed a comment that I think could be removed.

2024-07-01 22:19 UTC, kthompson23 approved these changes
Looks good, thank you.

2024-07-02 15:21 UTC, shawnmcknight commented on src/Connection.ts
> +export interface OpenOptions extends RequestOptions {
Removed

2024-07-02 15:59 UTC, philfuster approved these changes
LGTM! Thank you.

2024-07-02 16:41 UTC, merged